abi: ./abis/0xbb4.json
apiKey: XXXXXXXX
apiURL: https://api.bscscan.com
blockNumber: '19927225'
contractAddress: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c'
function: totalSupply()
networks:
  bsc:
    url: https://nd-615-585-235.p2pify.com/XXXXXXX
  eth:
    url: https://wandering-proud-bush.discover.quiknode.pro/xxx/
scanAPI:
  bsc:
    key: XXXXX
    url: https://api.bscscan.com
  eth:
    key: XXXXXXXX
    url: https://api.etherscan.io
url: https://nd-615-585-235.p2pify.com/XXXX
