address:
  PAIR: '0x02b0551B656509754285eeC81eE894338E14C5DD'
  ROUTER: '0x10ED43C718714eb63d5aA57B78B54704E256024E'
description: Description Template
interfaces:
- PancakeSwap/IERC20.sol
- PancakeSwap/IWETH.sol
networks:
  JSONRPC: http://127.0.0.1:8545
  blockNumber: '14433982'
  url: https://patient-dawn-thunder.bsc.discover.quiknode.pro/xxxxxxx/
parameters:
  amount: 100e18
  iterations: '5'
