/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ERC1820Registry,
  ERC1820RegistryInterface,
} from "../ERC1820Registry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_interfaceHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_implementer",
        type: "address",
      },
    ],
    name: "setInterfaceImplementer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ERC1820Registry__factory {
  static readonly abi = _abi;
  static createInterface(): ERC1820RegistryInterface {
    return new utils.Interface(_abi) as ERC1820RegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC1820Registry {
    return new Contract(address, _abi, signerOrProvider) as ERC1820Registry;
  }
}
